import test from 'node:test';
import assert from 'node:assert/strict';
import {createArchiveController} from './archive-controller.js';
const memo=id=>({id,text:`한글 ${id}`,revision:1,createdAtUnixMs:1,updatedAtUnixMs:1});
const item=id=>({...memo(id),title:id,preview:id});
const deferred=()=>{let resolve;const promise=new Promise(r=>{resolve=r;});return{promise,resolve};};
function fixture(overrides={}){let view;const api={list:async()=>({items:[item('a'),item('b')],total:2,invalidCount:0,nextOffset:null}),read:async id=>memo(id),remove:async()=>{},export:async()=>({saved:true}),...overrides};const controller=createArchiveController(api,value=>{view=value;});return{controller,get view(){return view;}};}
test('late read cannot replace a newer selection',async()=>{const delayed=deferred();const f=fixture({read:id=>id==='a'?delayed.promise:Promise.resolve(memo(id))});const old=f.controller.select('a');await f.controller.select('b');delayed.resolve(memo('a'));await old;assert.equal(f.view.selected.id,'b');});
test('actions reject duplicate submissions and freeze selection',async()=>{const pending=deferred();const f=fixture();await f.controller.select('a');let count=0;const action=f.controller.perform(()=>{count++;return pending.promise;});await f.controller.perform(async()=>{count++;});await f.controller.select('b');assert.equal(count,1);assert.equal(f.view.selected.id,'a');assert.equal(f.view.busy,true);pending.resolve(true);await action;assert.equal(f.view.busy,false);});
test('failed deletion keeps original selection and list',async()=>{const f=fixture({remove:async()=>{throw Error('locked');}});await f.controller.load();await f.controller.select('a');await assert.rejects(f.controller.remove('a'));assert.equal(f.view.items.length,2);assert.equal(f.view.selected.id,'a');assert.ok(f.view.error);});
test('deletion refreshes from the first page',async()=>{const offsets=[];let deleted=false;const f=fixture({list:async offset=>{offsets.push(offset);return{items:deleted?[item('b')]:[item('a'),item('b')],total:2,invalidCount:0,nextOffset:100};},remove:async()=>{deleted=true;}});await f.controller.load();await f.controller.remove('a');assert.deepEqual(offsets,[0,0]);assert.equal(f.view.items.length,1);});
test('disposed read never publishes stale content',async()=>{const pending=deferred();let publications=0;const controller=createArchiveController({list:async()=>({items:[],total:0,invalidCount:0,nextOffset:null}),read:()=>pending.promise,remove:async()=>{},export:async()=>({})},()=>publications++);const reading=controller.select('a');controller.dispose();pending.resolve(memo('a'));await reading;assert.equal(publications,1);});
test('successful export removes selection only after saved and removed ACK',async()=>{let exported=false;const f=fixture({export:async()=>{exported=true;return{saved:true,removed:true};},list:async()=>({items:exported?[item('b')]:[item('a'),item('b')],total:2,invalidCount:0,nextOffset:null})});await f.controller.load();await f.controller.select('a');await f.controller.exportMemo('a');assert.equal(f.view.selected,null);assert.deepEqual(f.view.items.map(x=>x.id),['b']);});
test('partial or failed export preserves selected memo for retry',async()=>{const f=fixture({export:async()=>({saved:true,removed:false})});await f.controller.select('a');await f.controller.exportMemo('a');assert.equal(f.view.selected.id,'a');const failed=fixture({export:async()=>{throw Error('disk_full');}});await failed.controller.select('a');await assert.rejects(failed.controller.exportMemo('a'));assert.equal(failed.view.selected.text,'한글 a');assert.equal(failed.view.busy,false);});
test('effect cleanup and setup can reconnect the controller',async()=>{const f=fixture();f.controller.dispose();f.controller.activate();await f.controller.load();assert.equal(f.view.items.length,2);});
test('failed schedule action preserves memo and permits a retry',async()=>{const f=fixture();await f.controller.load();await f.controller.select('a');await assert.rejects(f.controller.perform(async()=>{throw Error('connection_lost');}));assert.equal(f.view.selected.id,'a');assert.equal(f.view.items.length,2);assert.equal(f.view.busy,false);assert.equal(await f.controller.perform(async()=>true),true);assert.equal(f.view.error,'');});
