import type { QuestBoard } from "./types";

export const demoQuestBoard: QuestBoard = {
  schemaVersion: 1,
  activityDate: "2026-08-11",
  title: "Today’s quest log",
  generatedAt: "2026-08-11T09:05:00+09:00",
  sourceCoverage: "demo",
  quests: [
    {
      id: "confirm-direct-request",
      title: "Confirm the owner for a direct work request",
      project: "Inbox",
      category: "main",
      status: "needs_confirmation",
      summary: "A direct request is recorded, but the response owner is still unclear.",
      firstStep: "Write down the request, owner, and due date.",
      doneWhen: "The owner and reply requirement are recorded.",
      estimateMinutes: 15,
      points: 100,
      steps: [
        { id: "request-scope", label: "Capture the request scope", completed: false },
        { id: "request-owner", label: "Confirm the owner", completed: false },
      ],
      sourceLabel: "Daily note",
      sourcePath: "demo://daily-note",
      reports: [],
    },
    {
      id: "repair-reference-link",
      title: "Repair the learning-guide reference link",
      project: "Learning materials",
      category: "main",
      status: "in_progress",
      summary: "A historical link needs to point to a current supporting source.",
      firstStep: "Compare the old link with its replacement.",
      doneWhen: "The guide points to a working source.",
      estimateMinutes: 20,
      points: 120,
      steps: [
        { id: "link-locate", label: "Locate the old reference", completed: true },
        { id: "link-verify", label: "Verify its replacement", completed: false },
        { id: "link-update", label: "Record the verified change", completed: false },
      ],
      sourceLabel: "Daily note",
      sourcePath: "demo://daily-note",
      reports: [],
    },
    {
      id: "apply-module-template",
      title: "Apply the detailed explanation template",
      project: "Learning materials",
      category: "main",
      status: "not_started",
      summary: "Future modules should follow the same learner-facing explanation pattern.",
      firstStep: "Choose one module and apply the template.",
      doneWhen: "One module passes the checklist.",
      estimateMinutes: 30,
      points: 140,
      steps: [
        { id: "template-pick", label: "Choose the target module", completed: false },
        { id: "template-apply", label: "Apply the explanation pattern", completed: false },
      ],
      sourceLabel: "Daily note",
      sourcePath: "demo://daily-note",
      reports: [],
    },
    {
      id: "verify-manual-evidence",
      title: "Start a small evidence verification batch",
      project: "Knowledge review",
      category: "side",
      status: "not_started",
      summary: "A large verification queue is intentionally broken into a small first batch.",
      firstStep: "Select five entries with the clearest source links.",
      doneWhen: "The first five entries have a confirmed source outcome.",
      estimateMinutes: 45,
      points: 180,
      steps: [
        { id: "evidence-select", label: "Select five entries", completed: false },
        { id: "evidence-check", label: "Check each source", completed: false },
      ],
      sourceLabel: "Daily note",
      sourcePath: "demo://daily-note",
      reports: [],
    },
    {
      id: "wait-for-source-access",
      title: "Decide the official-source access path",
      project: "Knowledge review",
      category: "side",
      status: "paused",
      summary: "The work is paused until the permitted official source can be checked.",
      firstStep: "List the access or owner decision needed.",
      doneWhen: "The permitted source path is recorded.",
      estimateMinutes: 10,
      points: 80,
      steps: [{ id: "source-decision", label: "Record the access decision", completed: false }],
      sourceLabel: "Daily note",
      sourcePath: "demo://daily-note",
      reports: [],
    },
  ],
};
